plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}

application {
    mainClass = 'ru.mentee.power.crm.Main'
}

group = 'ru.mentee.power'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    junitVersion = '5.11.0'
    assertjVersion = '3.26.3'
    lombokVersion = '1.18.40'
    servletVersion = '6.1.0'
    tomcatVersion = '11.0.1'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation("org.junit.platform:junit-platform-launcher:1.13.4")

    // Lombok (для демонстрации, не используется в Sprint 1)
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // Mockito для тестов
    testImplementation 'org.mockito:mockito-core:5.21.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.21.0'

    constraints {
        testImplementation("net.bytebuddy:byte-buddy:1.17.5")
        testImplementation("net.bytebuddy:byte-buddy-agent:1.17.5")
    }

    implementation "jakarta.servlet:jakarta.servlet-api:${servletVersion}"
    implementation "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"
}

test {
    useJUnitPlatform()
}