plugins {
    id 'java'
    id 'jacoco'
    id 'application'
    id 'gg.jte.gradle' version '3.1.15'
    id 'org.springframework.boot' version '4.0.1'
}

application {
    mainClass = 'ru.mentee.power.crm.Main'
}

group = 'ru.mentee.power'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

configurations {
    servletOnly
}

ext {
    junitVersion = '5.11.0'
    assertjVersion = '3.26.3'
    lombokVersion = '1.18.40'
    servletVersion = '6.1.0'
    tomcatVersion = '11.0.1'
    jteVersion = '3.1.15'
    springBootVersion = '3.2.0'
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation "org.junit.jupiter:junit-jupiter:${junitVersion}"
    testImplementation "org.assertj:assertj-core:${assertjVersion}"
    testImplementation("org.junit.platform:junit-platform-launcher:1.13.4")

    // Lombok (для демонстрации, не используется в Sprint 1)
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"

    // Mockito для тестов
    testImplementation 'org.mockito:mockito-core:5.21.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.21.0'

    constraints {
        testImplementation("net.bytebuddy:byte-buddy:1.17.5")
        testImplementation("net.bytebuddy:byte-buddy-agent:1.17.5")
    }

    servletOnly "jakarta.servlet:jakarta.servlet-api:${servletVersion}"
    servletOnly "org.apache.tomcat.embed:tomcat-embed-core:${tomcatVersion}"

    //implementation "gg.jte:jte:${jteVersion}"
    //implementation "gg.jte:jte-runtime:${jteVersion}"

    // Sprint 5: Spring Boot Stack (BCORE-14)
    implementation platform("org.springframework.boot:spring-boot-dependencies:4.0.1")
    implementation "org.springframework.boot:spring-boot-starter-web"

    implementation "gg.jte:jte-spring-boot-starter-3:3.1.15"

    testImplementation "org.springframework.boot:spring-boot-starter-test"

    testImplementation "org.springframework.boot:spring-boot-starter-webmvc-test"

    implementation "jakarta.validation:jakarta.validation-api"
    implementation "org.hibernate.validator:hibernate-validator"

    // PostgreSQL JDBC Driver (для dev и production)
    runtimeOnly 'org.postgresql:postgresql'

    // H2 Database (только для тестов)
    testRuntimeOnly 'com.h2database:h2:2.3.232'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}
jte {
    sourceDirectory = file("src/main/jte").toPath()
    contentType = "Html"
    binaryStaticContent = false
}

test {
    useJUnitPlatform()
}

tasks.named("bootRun") {
    mainClass = 'ru.mentee.power.crm.spring.Application'
    classpath = sourceSets.main.runtimeClasspath - configurations.servletOnly
}

tasks.named("run") {
    classpath += configurations.servletOnly
}