server:
  port: 8081

gg:
  jte:
    developmentMode: true

spring:
  application:
    name: mentee-power-crm

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
      ddl-auto: validate

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE